site_name: Documentación
site_description: Documentación técnica del equipo OPRobots de robótica
site_author: robotaleh
site_url: https://docs.oprobots.org

repo_name: OPRobots/docs

theme:
  name: material
  custom_dir: docs/assets/templates
  language: es
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Modo claro
  features:
    - navigation.instant
    - navigation.top
    - toc.follow
    - search.highlight
    - content.code.copy
  logo: assets/opr_logo.png
  favicon: assets/imgs/favicon/favicon.ico
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_generic_format

extra_javascript:
  - assets/js/header-title.js
  - assets/js/mermaid-zoom.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - assets/js/math-render.js

extra_css:
  - assets/css/custom.css
  - assets/css/mermaid-zoom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css

validation:
  links:
    not_found: ignore

plugins:
  - search
  - monorepo

nav:
  - Inicio: index.md
  - Demos:
      - CRSF-demo: '!include docs/demos/CRSF-demo/mkdocs.yml'
      - H3LIS331-demo: '!include docs/demos/H3LIS331-demo/mkdocs.yml'
      - SRAM-demo: '!include docs/demos/SRAM-demo/mkdocs.yml'
  - Módulos:
      - IRStart: '!include docs/modules/IRStart/mkdocs.yml'
  - Robots:
      - FujitoraBot2: '!include docs/robots/FujitoraBot2/mkdocs.yml'
      - ZoroBot3: '!include docs/robots/ZoroBot3/mkdocs.yml'
